# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\AppUser:
        algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      my_db_provider:
        entity:
          class: AppBundle:AppUser
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/login_check
            stateless: true
            guard:
              provider: my_db_provider
              authenticators:
                - app.authenticator.user
        app:
          anonymous: false
          pattern: ^/post
          stateless: true
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator

