# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.authenticator.user:
    class: AppBundle\Security\Authenticator\UserLoginAuthenticator
    arguments: ['@doctrine.orm.entity_manager','@security.password_encoder','@lexik_jwt_authentication.handler.authentication_failure','@lexik_jwt_authentication.handler.authentication_success']